version: '3'

services:

    ####################################################################################################################
    # PinguTrain Bot                                                                                        #
    ####################################################################################################################
    pingutrain-bot:
        container_name: pingutrain-bot
        build: ./PinguTrainBot
        environment:
            PINGU_TRAIN_BOT_TELEGRAM_TOKEN: 5380143925:AAGp11WkxUT0-2tNWGqTc-8lrh34gME3Bnc
            PINGU_TRAIN_BOT_TELEGRAM_NAME: PinguTrainBot
            PINGU_TRAIN_BOT_MONGODB_HOST: mongodb
            PINGU_TRAIN_BOT_MONGODB_PORT: 27017
            PINGU_TRAIN_BOT_MONGODB_USERNAME: root
            PINGU_TRAIN_BOT_MONGODB_PASSWORD: 12345
            PINGU_TRAIN_BOT_QUEUE_UPDATES: updates
            PINGU_TRAIN_BOT_QUEUE_ACTIONS: actions
            PINGU_TRAIN_BOT_RABBITMQ_HOST: rabbitmq
            PINGU_TRAIN_BOT_RABBITMQ_PORT: 5672
            PINGU_TRAIN_BOT_RABBITMQ_USERNAME: user
            PINGU_TRAIN_BOT_RABBITMQ_PASSWORD: 12345
        depends_on:
            - mongodb
            - rabbitmq
        links:
            - mongodb
            - rabbitmq
        ports:
            - "8080:8080"
            - "5005:5005"

    ####################################################################################################################
    # RabbitMQ                                                                                                        #
    ####################################################################################################################
    rabbitmq:
        container_name: rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: 12345
        hostname: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
            - 5672:5672
            - 15672:15672

    ####################################################################################################################
    # MongoDB                                                                                                          #
    ####################################################################################################################
    mongodb:
        container_name: mongodb
        hostname: mongodb
        image: amd64/mongo:5
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 12345
        ports:
            - "27017:27017"
        volumes:
            - mongodb-volume:/data/db


volumes:
    mongodb-volume:
